vortexgin_user_create:
    path:     /create
    defaults: { _controller: VortexginUserBundle:User:create }
    requirements:
        _method: POST
vortexgin_user_read:
    path:     /read
    defaults: { _controller: VortexginUserBundle:User:read }
    requirements:
        _method: GET
vortexgin_user_update:
    path:     /update/{id}
    defaults: { _controller: VortexginUserBundle:User:update, id: 0 }
    requirements:
        _method: PATCH
vortexgin_user_delete:
    path:     /delete/{id}
    defaults: { _controller: VortexginUserBundle:User:delete, id: 0 }
    requirements:
        _method: DELETE
