services:
    vortexgin.user.manager.user:
        class: Vortexgin\UserBundle\Manager\UserManager
        arguments:
            - @service_container
            - %vortexgin.user.user_class%
    vortexgin.user.manager.user.mongo:
        class: Vortexgin\UserBundle\Manager\UserMongoManager
        arguments:
            - @service_container
            - %vortexgin.user.user_document%