admin_login:
    pattern:  /login
    defaults: { _controller: VortexginAdminBundle:Security:login }
admin_login_check:
    pattern:  /login_check
    defaults: { _controller: VortexginAdminBundle:Security:check }
admin_logout:
    pattern:  /logout
    defaults: { _controller: VortexginAdminBundle:Security:logout }
    
vortexgin_auth_login:
    path:     /login
    defaults: { _controller: VortexginAuthBundle:Default:login }
    requirements:
        _method: POST
vortexgin_auth_logout:
    path:     /logout
    defaults: { _controller: VortexginAuthBundle:Default:logout }
    requirements:
        _method: POST
vortexgin_auth_validate:
    path:     /validate
    defaults: { _controller: VortexginAuthBundle:Default:validate }
    requirements:
        _method: POST
