services:
    vortexgin.security.user_provider:
        class: Vortexgin\AuthBundle\AuthProvider\UserProvider
        arguments:
            - @vortexgin.user.manager.user
            - @vortexgin.oauth.manager.token
    vortexgin.security.user_authenticator:
        class: Vortexgin\AuthBundle\AuthAuthenticator\UserAuthenticator
        arguments:
            - @security.http_utils
        public: false
    vortexgin.oauth.manager.client:
        class: Vortexgin\AuthBundle\Manager\OAuthClientManager
        arguments:
            - @service_container
            - %vortexgin.oauth.client_class%
    vortexgin.oauth.manager.token:
        class: Vortexgin\AuthBundle\Manager\OAuthTokenManager
        arguments:
            - @service_container
            - %vortexgin.oauth.token_class%
