vortexgin_core:
    host: http://localhost:9006/
    uploads:
        dir: uploads/
    image:
        mime_types:
            - image/jpg
            - image/jpeg
            - image/pjpeg
            - image/gif
            - image/png
    kilatstorage:
        access_key: 123
        secret_key: 123
