vortexgin_provinsi_create:
    path:     /provinsi
    defaults: { _controller: VortexginLocationBundle:Provinsi:create }
    requirements:
        _method: POST
vortexgin_provinsi_read:
    path:     /provinsi
    defaults: { _controller: VortexginLocationBundle:Provinsi:read }
    requirements:
        _method: GET
vortexgin_provinsi_update:
    path:     /provinsi/{id}
    defaults: { _controller: VortexginLocationBundle:Provinsi:update, id: 0 }
    requirements:
        _method: PATCH
vortexgin_provinsi_delete:
    path:     /provinsi/{id}
    defaults: { _controller: VortexginLocationBundle:Provinsi:delete, id: 0 }
    requirements:
        _method: DELETE

vortexgin_kota_create:
    path:     /kota
    defaults: { _controller: VortexginLocationBundle:Kota:create }
    requirements:
        _method: POST
vortexgin_kota_read:
    path:     /kota
    defaults: { _controller: VortexginLocationBundle:Kota:read }
    requirements:
        _method: GET
vortexgin_kota_update:
    path:     /kota/{id}
    defaults: { _controller: VortexginLocationBundle:Kota:update, id: 0 }
    requirements:
        _method: PATCH
vortexgin_kota_delete:
    path:     /kota/{id}
    defaults: { _controller: VortexginLocationBundle:Kota:delete, id: 0 }
    requirements:
        _method: DELETE

vortexgin_area_create:
    path:     /area
    defaults: { _controller: VortexginLocationBundle:Area:create }
    requirements:
        _method: POST
vortexgin_area_read:
    path:     /area
    defaults: { _controller: VortexginLocationBundle:Area:read }
    requirements:
        _method: GET
vortexgin_area_update:
    path:     /area/{id}
    defaults: { _controller: VortexginLocationBundle:Area:update, id: 0 }
    requirements:
        _method: PATCH
vortexgin_area_delete:
    path:     /area/{id}
    defaults: { _controller: VortexginLocationBundle:Area:delete, id: 0 }
    requirements:
        _method: DELETE
