services:
    ds.location.manager.provinsi:
        class: DS\LocationBundle\Manager\ProvinsiManager
        arguments:
            - @service_container
            - %ds.location.provinsi_class%
    ds.location.manager.kota:
        class: DS\LocationBundle\Manager\KotaManager
        arguments:
            - @service_container
            - %ds.location.kota_class%
            - @ds.location.manager.provinsi
    ds.location.manager.area:
        class: DS\LocationBundle\Manager\AreaManager
        arguments:
            - @service_container
            - %ds.location.area_class%
            - @ds.location.manager.kota
