services:
    vortexgin.location.manager.provinsi:
        class: Vortexgin\LocationBundle\Manager\ProvinsiManager
        arguments:
            - @service_container
            - %vortexgin.location.provinsi_class%
    vortexgin.location.manager.kota:
        class: Vortexgin\LocationBundle\Manager\KotaManager
        arguments:
            - @service_container
            - %vortexgin.location.kota_class%
            - @vortexgin.location.manager.provinsi
    vortexgin.location.manager.area:
        class: Vortexgin\LocationBundle\Manager\AreaManager
        arguments:
            - @service_container
            - %vortexgin.location.area_class%
            - @vortexgin.location.manager.kota
